FROM node:10-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

RUN chmod +x /home/node/app/wait-for.sh

EXPOSE 3500

CMD ["node", "app.js"]
